// TODO: className did not match 문제 해결해야 한다.
'use client'
import './globals.css'
// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { ThemeProvider } from 'styled-components'
import StyledComponentsRegistry from 'app/lib/registry.tsx'

import { theme } from 'themes'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ThemeProvider>
      </body>
    </html>
  )
}
