// CHECKLIST : className did not match 문제 해결
import type { Metadata } from 'next'
import StyledComponentsRegistry from 'lib/registry.tsx'
import './globals.css'

import ThemeClient from 'lib/theme.tsx'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeClient>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ThemeClient>
      </body>
    </html>
  )
}
